export const styles = {
  introPageSubContainerOne: {
    width: "45%",
    paddingLeft: "120px",
    paddingTop: "60px",
    paddingRight: "60px",
  },
  introPageSubContainerTwo: {
    width: "55%",
  },
  introPageContainer: {
    display: "flex",
    flexDirection: "row",
    height: "540px",
  },
  introHeaderStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  introHeaderImageContainerStyle: {
    fill: "#fc8019",
  },
  loginButtonStyle: {
    backgroundColor: "#fff",
    color: "#000",
    textDecoration: "none",
    cursor: "pointer",
    display: "inline-block",
    textAlign: "center",
    fontWeight: "600",
    height: "40px",
    lineHeight: "40px",
    width: "auto",
    padding: "0 2rem",
    border: 'none',
  },
  signupButtonStyle: {
    backgroundColor: "#000",
    color: "#fff",
    boxShadow: "0 1px 3px 0 rgb(0 0 0 / 12%)",
    textDecoration: "none",
    cursor: "pointer",
    display: "inline-block",
    textAlign: "center",
    fontWeight: "600",
    height: "40px",
    lineHeight: "40px",
    width: "auto",
    padding: "0 2rem",
    border: 'none',
  },
  textOneStyle: {
    marginTop: "60px",
    marginBottom: "0",
    fontSize: "40px",
    fontWeight: "600",
    letterSpacing: "-.45px",
  },
  textTwoStyle: {
    fontSize: "24px",
    fontWeight: "300",
    width: "600px",
    marginTop: "0",
    marginBottom: "0",
    lineHeight: "40px",
    letterSpacing: ".3px",
    color: "#686b78",
  },
  findFoodButtonStyle: {
    cursor: "pointer",
    display: "inline-block",
    textAlign: "center",
    border: "none",
    color: "#fff",
    backgroundColor: "#fc8019",
    right: "0",
    height: "60px",
    lineHeight: "60px",
    width: "140px",
    fontSize: "16px",
    fontWeight: "bolder",
    letterSpacing: ".53px",
    padding: "0",
  },
  inputTagContainerStyle: {
    display: "flex",
    flexDirection: "row",
    height: "58px",
    marginTop: "35px",
  },
  inputTagStyle: {
    border: "1px solid #bebfc5",
    height: "100%",
    padding: "0 5px",
    lineHeight: "28px",
    paddingTop: "0",
    paddingLeft: "25px",
    paddingRight: "170px",
    caretColor: "#fc8019",
    fontSize: "18px",
    fontWeight: "500",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    borderRight: "0",
    color: "#686b78",
  },
  locateMeStyle: {
    width: "80px",
    border: "1px solid #bebfc5",
    borderLeft: "0",
    height: "100%",
    display: "flex",
    alignItems: "center",
    fontWeight: "500",
    fontSize: "14px",
    cursor: "pointer",
    letterSpacing: "-.35px",
    color: "#686b78",
  },
  inputContainer: {
    display: "flex",
    flexDirection: "row",
  },
  introPageSecondContainer: {
    background: "#2b1e16",
    padding: "0 120px",
  },
  secondContainerImageOneStyle: {
    width: "105px",
    height: "199px",
  },
  secondContainerImageTwoStyle: {
    width: "112px",
    height: "206px",
  },
  secondContainerImageThreeStyle: {
    width: "124px",
    height: "188px",
  },
  imageContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: "80px",
  },
  introPageThirdContainer: {
    display: "flex",
    justifyContent: "space-around",
    height: "570px",
    overflow: "hidden",
    padding: "0 20px",
  },
  thirdContainerHeadingStyle: {
    fontSize: "40px",
    fontWeight: "600",
    lineHeight: "1",
    letterSpacing: "-.45px",
    width: "300px",
  },
  subContainerStyle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "0px 80px",
  },
  secondSubContainerStyle: {
    display: "flex",
    justifyContent: "flex-end",
  },
  thirdContainerSubHeadingStyle: {
    fontSize: "20px",
    fontWeight: "300",
    paddingTop: "20px",
    paddingBottom: "60px",
    color: "#7e808c",
    lineHeight: "1.2",
    width: "400px",
  },
  linkContainerStyle: {
    display: "flex",
    justifyContent: "space-between",
    width: "400px",
  },
  thirdContainerImageOneStyle: {},
  thirdContainerImageTwoStyle: {
    display: "flex",
    alignItems: "flex-end",
  },
  modalCrossButtonStyle: {
    display: "flex",
    alignItems: "center",
    paddingLeft: "34px",
    paddingTop: "30px",
    paddingRight: "124px",
    cursor: "pointer",
  },
  modalContainerStyle: {
    display: "flex",
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: '30px',
  },
  modalLoginTextStyle: {
    marginTop: "15px",
    fontSize: "30px",
    fontWeight: "500",
  },
  modalDividerStyle: {
    content: "",
    width: '30px',
    border: '1px solid #000',
    marginTop: "18px",
  },
  modalSubTextContainerStyle: {
    display: "flex",
    flexDirection: "row",
    fontSize: "14px",
    marginTop: "10px",
  },
  modalOrTextStyle: { marginRight: "5px" },
  modalCreateAccTextStyle: {
    fontWeight: "500",
    cursor: "pointer",
    color: "#fc8019",
  },
  modalLoginButtonStyle: {
    cursor: "pointer",
    display: "inline-block",
    textAlign: "center",
    border: "none",
    color: "#fff",
    backgroundColor: "#fc8019",
    right: "0",
    height: "60px",
    lineHeight: "60px",
    width: "100%",
    fontSize: "16px",
    fontWeight: "bolder",
    letterSpacing: ".53px",
    padding: "0",
  }
};
